services:

  multi-role-auth-laravel-11-using-breeze:
    container_name: multi-role-auth-laravel-11-using-breeze
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./laravel-app:/var/www/html
    ports:
      - 8002:80
    depends_on:
      - mysql_db
      - nodejs
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql_db
      DB_PORT: 3306
      DB_DATABASE: multi-role-auth-laravel-11-using-breeze
      DB_USERNAME: root
      DB_PASSWORD: root
    
  mysql_db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: multi-role-auth-laravel-11-using-breeze
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 8003:80
    environment:
      - PMA_ARBITRARY=1

  nodejs:
    image: node:latest
    volumes:
      - ./laravel-app:/var/www/html
