services:

  multi-role-auth-laravel-11-using-breeze:
    container_name: multi-role-auth-laravel-11-using-breeze
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./laravel-app:/var/www/html
    ports:
      - 8002:80
    
  mysql_db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: multi-role-auth-laravel-11-using-breeze
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 8003:80
    environment:
      - PMA_ARBITRARY=1